spring:
  application:
    name: techefx-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vmcit/environment-variable-repo.git


server:
  port: ${port:8889}

